### ISSUE TITLE
Can you add me as an npm maintainer on jstransformer-lodash?

### ISSUE THREAD

**Issue by RobLoach** [tunnckoCore/ama#7]
https://github.com/jstransformers/jstransformer-lodash/issues/6
https://www.npmjs.com/package/jstransformer-lodash

**Comment by tunnckoCore** [comment]
yep. it's strange anyway.

**Comment by tunnckoCore** [comment]
@RobLoach strange...

```
npm ERR! You do not have permission to publish 'jstransformer-lodash'. Are you logged in as the correct user? : jstransformer-lodash
```

There's no owners on that package? Haha! If this is possible, would be awful, really. I want to believe it's impossible to have no owners, otherwise.. we found very strange bug in the npm.

And yes, im logged in the correct user. I have only one account.

PS: It seem, all you guys are owners, as expected :)

```
[charlike@localhost jstransformer-lodash]$ npm owner ls jstransformer-lodash
forbeslindesay <forbes@lindesay.co.uk>
hemanth <hemanth.hm@gmail.com>
robloach <robloach@gmail.com>
stoeffel <schtoeffel@gmail.com>
timothygu <timothygu99@gmail.com>
```

**Comment by tunnckoCore** [comment]
But yea, sad truth

```
[charlike@localhost jstransformer-lodash]$ npm ls jstransformer-lodash
jstransformer-lodash@0.1.0 /home/charlike/dev/jstransformer-lodash
└── (empty)
```

**Comment by RobLoach** [comment]
Bizarre... npmjs.com cached?
